"""
Django settings for helloworldproject project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#プロジェクトごとに生成される秘密の鍵
SECRET_KEY = 'h$=$l1&op%ay0*)1n0g(_3#o(640g69jz=kw_1%j7_2b_du3g1'

# SECURITY WARNING: don't run with debug turned on in production!
# 公開するときはfalseにする。不必要な情報を部外者に与えてしまうため
# tureのとき、エラー情報が詳細にブラウザに表示される
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

#adminは管理画面
#プロジェクトの機能群
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# 上級向け(?)セッションの管理などに使用したり、、
# ミドルウェア=何か処理が行われるとき、間に入って何かしれくれるもの
# セッション=ログインしたユーザがログインした状態をブラウザが記憶しておく機能
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#まず最初に呼び出すフォルダとファイルをを指定。
#ブラウザから最初に呼び出されるもの
ROOT_URLCONF = 'helloworldproject.urls'

#templateがどこにあるか
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR,'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# wsgiがどこにあるか
WSGI_APPLICATION = 'helloworldproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# データベースがどこにあるか
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
#パスワードのvalidationの管理をここでしている(短すぎたりとか)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
#timezone(住んでるところ)、言語など
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# cssファイルや画像ファイルを呼び出すとき、どこから呼び出すか
STATIC_URL = '/static/'
